### ISSUE TITLE
Add Multilingual Datasets

### ISSUE THREAD

**Issue by NickSchoelkopf** [Yale-LILY/SummerTime#112]
We currently have only 1 multilingual dataset with 5 languages, but have multilingual models that theoretically support many more than that. I would like to implement:

-  [XLSum (45 languages)](https://huggingface.co/datasets/csebuetnlp/xlsum) which is already in Huggingface
- [MassiveSumm (92 languages)](https://github.com/danielvarab/massive-summ) which is not in Huggingface

So that we have a much greater spread of multilingual data to test on.

**Comment by niansong1996** [comment]
@NickSchoelkopf Is this done? Seems like we can close this?

**Comment by NickSchoelkopf** [comment]
@niansong1996 Yes, this can be closed!
