### ISSUE TITLE
Spacy Version Conflict

### ISSUE THREAD

**Issue by chatc** [Yale-LILY/SummerTime#37]
SummTime uses Spacy 3 while HMNet uses Spacy 2. However, there are several differences between these two versions which are similar to Python 2 and Python 3. Hence, we need to either adapt one of two versions or find a way to use both of them.

**Comment by niansong1996** [comment]
@chatc How hard is it to adapt HMNet to Spacy 3? 

@troyfeng116 I think you dealt with a similar issue before?

**Comment by troyfeng116** [comment]
For the most part, SpaCy is backwards compatible. @chatc are you having issues with pip installation, or with actually running on spacy==3x?

**Comment by chatc** [comment]
It’s not hard to adapt HMNet to Spacy 3. I will try to modify it to the Spacy 3 version. Thanks! @niansong1996 

There are several running issues. I am sorry that I am not quite familiar with this package, but I found the following errors:
`nlp = spacy.load('en', parser = False) : TypeError: load() got an unexpected keyword argument 'parser'`
`nlp.tagger.labels AttributeError: 'English' object has no attribute 'tagger'`
But it is okay since I am planning to change the version of Spacy in HMNet to 3 @troyfeng116
