### ISSUE TITLE
Can i specify dataset path in datasetclass?

### ISSUE THREAD

**Issue by epsilon-deltta** [Yale-LILY/SummerTime#74]
```
import dataset
arxdt = dataset.ArxivDataset()
```
In this, this default saved path is /home/$username/.cache/huggingface/datasets/summertime_arxiv.
Can I specify a certain path when downloading and loading the dataset?

**Comment by troyfeng116** [comment]
@epsilon-deltta  You can create an environment variable `HF_HOME` specifying where you want `.cache`. i.e. `export HF_HOME=path/to/somewhere/.cache`

**Comment by MuroriM** [comment]
@epsilon-deltta Do you want to change the path for only a certain dataset or for all datasets?

**Comment by epsilon-deltta** [comment]
@troyfeng116  thank you. I solved my problem cuz of you 😁😁.  But, i hoped to change the path in the programming level, not the system level.
I mean like this 
```
import dataset
arxdt = dataset.ArxivDataset(path = path/to/somewhere) # default is ~/.cache/huggingface/datasets
```
