### ISSUE TITLE
Documentation for HMNetModel

### ISSUE THREAD

**Issue by ismu** [Yale-LILY/SummerTime#76]
HI :)

I would like know how to use HMNetModel for dialogues. 

I have code:
```
from model import HMNetModel

hmn = HMNetModel()
print(hmn.summarize(dial))
```

How should `dial` looks like? Can I get `dial` from `CNN/DM(3.0.0)` dataset?

Thanks in advance for your help :)

**Comment by niansong1996** [comment]
Hi, more documentation and optimization for HMNet is added in #79. 

More specifically, you can refer to `tests/model_test.py` or [here](https://github.com/Yale-LILY/SummerTime/blob/main/tests/model_test.py#L58) for more detailed usage of HMNet.

**Comment by ismu** [comment]
All clear :)
