### ISSUE TITLE
Could you provide train code

### ISSUE THREAD

**Issue by epsilon-deltta** [Yale-LILY/SummerTime#80]
I want to do BART  finetuning on my dataset,
Could you provide a snippet of the train code? 
And, I also want to do pre-training on another dataset. If there is, could you send me a link.

**Comment by niansong1996** [comment]
Hi @epsilon-deltta, at current stage, SummerTime does not support fine-tuning/pre-training yet. Though we see this as important future work, it is unlikely that we are going to complete it in the next month or two. 

Please refer to other implementations, such as [huggingface](https://github.com/huggingface/transformers) or [fairseq](https://github.com/pytorch/fairseq).

**Comment by niansong1996** [comment]
Closed due to inactivity.
